### PR TITLE
enable persistent uefi state support#170

### PR DESCRIPTION
**Pull request by DanielFroehlich**

### CODE REVIEW

**Comment by rbo** [comment]
Does it mean every VM need an extra 12 MB storage to persist uefi? Or is this configure at vm level as well?

**Comment by DanielFroehlich** [comment]
> Does it mean every VM need an extra 12 MB storage to persist uefi? Or is this configure at vm level as well?

This PR here is just the base config for the cluster. It has to be enable at the vm level to be in effect (and create that state PVC). You do that in the VM domain spec like this:

```
        firmware:
          bootloader:
            efi:
              persistent: true
```

Which btw currently breaks cloneing - you cant clone a VM with persistet state.

**Comment by DanielFroehlich** [comment]
this now also add observability to ACM support#135

**Comment by rbo** [comment]
LGMT

**Pull request merged**
